spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:8931/bestellingservice
    username: root
    password: root
  rabbitmq:
    username: Kantilever
    password: Kant1lever
    host: 192.168.178.158
    port: 8920
  jpa:
    hibernate:
      ddl-auto: create-drop
  # LocalDateTime fix Jackson https://stackoverflow.com/a/29959842/5473627
  # Example yyyy-MM-dd HH:mm:ss
  jackson:
    serialization:
      write_dates_as_timestamps: false
  # Used for Security
  aop:
    proxy-target-class: true

urls:
  webwinkel: "localhost:8081"
  account: "localhost:9999"

server:
  port: 8082

# Security properties
tokens:
  accessToken:
    secret: "hQWcnjr1LAbgNX7HBujEnbdbbt0_Y6z5m8eoEQAy275s4TBNHUVXN4OnOQQKjWlUOUNPRszHumXK7FRGyMnq9vcDsTfHmpsDrSv5F5zcVWUi2_VwJaneCeBCQKqqQxwcSumoDWcZEQ3aCNtZ5KFc-6LrIr9tliTqxlpPRSGUAY__1tbzBeW43I5LTnTnVzqwc3KJ8UpytDNnS8x1nm5wos7lHym6qiK7CmqohxySMul1ZeSBp274G2pOA008H7ehxmDEGbsy3K7BSV-hUF_5K88WRwQqRhgg_bucAuGEH_fUodxtadF4mlf_7A7-DC6LsOPkjqnis2bFGyEDbcctRg"

logging:
  level:
    nl:
      kantilever: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
