---
version: '3'
services:

  de-jong-webwinkel-mysql:
    image: 'bitnami/mysql:latest'
    container_name: de-jong-webwinkel-mysql
    ports:
      - "8925:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webwinkelservice

  de-jong-webwinkel-phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
    - "8926:80"
   links:
     - de-jong-webwinkel-mysql:db

  de-jong-webwinkel:
    build:
      context: .
      dockerfile: ops/Java/Dockerfile
      args:
        - DIRECTORY=webwinkel
    command: sh ./wait-for.sh --timeout=300 de-jong-webwinkel-mysql:3306 -- java -jar app.jar
    ports:
      - "8927:8081"
    environment:
      - spring_datasource_url=jdbc:mysql://de-jong-webwinkel-mysql:3306/webwinkelservice
    depends_on:
      - de-jong-webwinkel-mysql

  de-jong-front-end-webwinkel:
    build:
      context: .
      dockerfile: ops/Polymer/Dockerfile
      args:
        - DIRECTORY=front-end-webwinkel
    ports:
      - "8928:80"

  de-jong-replayservice:
      build:
        context: .
        dockerfile: ops/Java/Dockerfile
        args:
          - DIRECTORY=replayservice
      command: java -jar app.jar
      ports:
        - "8929:8080"

  de-jong-bestellingservice:
    build:
      context: .
      dockerfile: ops/Java/Dockerfile
      args:
        - DIRECTORY=bestellingservice
    command: sh ./wait-for.sh --timeout=300 de-jong-bestellingservice-mysql:3306 -- java -jar app.jar
    ports:
      - "8930:8082"
    environment:
      - spring_datasource_url=jdbc:mysql://de-jong-bestellingservice-mysql:3306/bestellingservice
      - urls_webwinkel=de-jong-webwinkel:8081
    depends_on:
      - de-jong-bestellingservice-mysql

  de-jong-bestellingservice-mysql:
    image: 'bitnami/mysql:latest'
    container_name: de-jong-bestellingservice-mysql
    ports:
      - "8931:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bestellingservice

  de-jong-bestellingservice-phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
    - "8932:80"
   links:
     - de-jong-bestellingservice-mysql:db

  de-jong-front-end-commercieel-manager:
     build:
       context: .
       dockerfile: ops/Polymer/Dockerfile
       args:
         - DIRECTORY=front-end-commercieel-manager
     ports:
       - "8933:80"

  de-jong-front-end-commercieel-manager:
    build:
      context: .
      dockerfile: ops/Polymer/Dockerfile
      args:
        - DIRECTORY=front-end-inpakken
    ports:
      - "8934:80"

  de-jong-accountservice-mysql:
    image: 'bitnami/mysql:latest'
    container_name: de-jong-accountservice-mysql
    ports:
     - "8935:3306"
    environment:
     - MYSQL_ROOT_USER=root
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=accountservice

  de-jong-accountservice-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
     - "8936:80"
    links:
      - de-jong-accountservice-mysql:db

  de-jong-accountservice:
    build:
     context: .
     dockerfile: ops/Java/Dockerfile
     args:
       - DIRECTORY=accountservice
    command: sh ./wait-for.sh --timeout=300 de-jong-accountservice-mysql:3306 -- java -jar app.jar
    ports:
     - "8937:9999"
    environment:
     - spring_datasource_url=jdbc:mysql://de-jong-accountservice-mysql:3306/accountservice
    depends_on:
     - de-jong-accountservice-mysql


