---
version: '3'
services:

  de-jong-webwinkel-mysql:
    image: 'bitnami/mysql:latest'
    container_name: de-jong-webwinkel-mysql
    ports:
      - "8925:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webwinkelservice

  de-jong-webwinkel-phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
    - "8926:80"
   links:
     - de-jong-webwinkel-mysql:db

  de-jong-webwinkel:
    build:
      context: .
      dockerfile: ops/Java/Dockerfile
      args:
        - DIRECTORY=webwinkel
    command: sh ./wait-for.sh --timeout=300 de-jong-webwinkel-mysql:3306 -- java -jar app.jar
    ports:
      - "8927:8081"
    environment:
      - spring_datasource_url=jdbc:mysql://de-jong-webwinkel-mysql:3306/webwinkelservice
    depends_on:
      - de-jong-webwinkel-mysql

  de-jong-front-end-webwinkel:
    build:
      context: .
      dockerfile: ops/Polymer/Dockerfile
    ports:
      - "8928:80"

  de-jong-replayservice:
      build:
        context: .
        dockerfile: ops/Java/Dockerfile
        args:
          - DIRECTORY=replayservice
      command: java -jar app.jar
      ports:
        - "8929:8080"

  de-jong-bestellingservice:
    build:
      context: .
      dockerfile: ops/Java/Dockerfile
      args:
        - DIRECTORY=bestellingservice
    command: sh ./wait-for.sh --timeout=300 de-jong-bestellingservice-mysql:3306 -- java -jar app.jar
    ports:
      - "8930:8082"
    environment:
      - spring_datasource_url=jdbc:mysql://de-jong-bestellingservice-mysql:3306/bestellingservice
    depends_on:
      - de-jong-webwinkel-mysql

  de-jong-bestellingservice-mysql:
    image: 'bitnami/mysql:latest'
    container_name: de-jong-bestellingservice-mysql
    ports:
      - "8931:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bestellingservice

  de-jong-bestellingservice-phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
    - "8932:80"
   links:
     - de-jong-bestellingservice-mysql:db
