---
version: '3'
services:

  de-jong-mysql:
    container_name: de-jong-mysql
    image: 'bitnami/mysql:latest'
    ports:
      - "8925:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webshop_kantilever

  de-jong-phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
    - "8926:80"
   links:
     - de-jong-mysql:db
