---
version: '3'
services:

  de-jong-mysql:
    container_name: de-jong-mysql
    image: 'bitnami/mysql:latest'
    ports:
      - "8925:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webshop_kantilever

  de-jong-phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
    - "8926:80"
   links:
     - de-jong-mysql:db

  front-end-webwinkel:
    build:


#  de-jong-fe-webwinkel:
#    image



#  jeruno-spring-pcs_onderhoud:
#    build: pcs_onderhoud/
#    container_name: jeruno-spring-pcs_onderhoud
#    command: sh ./wait-for.sh --timeout=300 ${MYSQL_HOST}:${MYSQL_PORT} -- sh ./wait-for.sh --timeout=300 ${RABBIT_HOST}:${RABBIT_PORT} -- java -jar app.jar
#    ports:
#      - "8924:8924"
#    environment:
#      - MYSQL_HOST=${MYSQL_HOST}
#      - MYSQL_PORT=${MYSQL_PORT}
#      - RABBIT_HOST=${RABBIT_HOST}
#      - RABBIT_PORT=${RABBIT_PORT}
#    depends_on:
#      - jeruno-mysql
#      - jeruno-rabbitmq
