---
version: '3'
services:

  de-jong-phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
    - "8925:80"
   links:
     - de-jong-webwinkel-mysql:db

  de-jong-webwinkel-mysql:
    container_name: de-jong-mysql
    image: 'bitnami/mysql:latest'
    ports:
      - "8926:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webwinkel

  de-jong-webwinkel:
    build:
      context: .
      dockerfile: ops/Webwinkel/Dockerfile
    container_name: de-jong-webwinkel
    command: sh ./wait-for.sh --timeout=300 de-jong-webwinkel-mysql:3306 -- java -jar app.jar
    ports:
      - "8927:8080"
    environment:
      - MYSQL_HOST=de-jong-webwinkel-mysql
      - MYSQL_PORT=3306
    depends_on:
      - de-jong-webwinkel-mysql

  de-jong-front-end-webwinkel:
    build:
      context: .
      dockerfile: ops/Polymer/Dockerfile
    ports:
      - "8928:80"


#  de-jong-fe-webwinkel:
#    image




