---
version: '2'
services:

  de-jong-rabbitmq:
    container_name: de-jong-rabbitmq
    image: rabbitmq:3-management
    ports:
     - "8920:5672"
     - "8921:15672"

  de-jong-mysql:
    container_name: de-jong-mysql
    image: 'bitnami/mysql:latest'
    ports:
      - "8922:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webshop_kantilever

  de-jong-phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
    - "8923:80"
   links:
     - de-jong-mysql:db



#  jeruno-spring-pcs_onderhoud:
#    build: pcs_onderhoud/
#    container_name: jeruno-spring-pcs_onderhoud
#    command: sh ./wait-for.sh --timeout=300 ${MYSQL_HOST}:${MYSQL_PORT} -- sh ./wait-for.sh --timeout=300 ${RABBIT_HOST}:${RABBIT_PORT} -- java -jar app.jar
#    ports:
#      - "8924:8924"
#    environment:
#      - MYSQL_HOST=${MYSQL_HOST}
#      - MYSQL_PORT=${MYSQL_PORT}
#      - RABBIT_HOST=${RABBIT_HOST}
#      - RABBIT_PORT=${RABBIT_PORT}
#    depends_on:
#      - jeruno-mysql
#      - jeruno-rabbitmq
