---
version: '3'
services:

  de-jong-webwinkel-mysql:
    image: 'bitnami/mysql:latest'
    container_name: de-jong-webwinkel-mysql
    ports:
      - "8925:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webwinkelservice

  de-jong-webwinkel-phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
    - "8926:80"
   links:
     - de-jong-webwinkel-mysql:db

  de-jong-bestellingservice-mysql:
    image: 'bitnami/mysql:latest'
    container_name: de-jong-bestellingservice-mysql
    ports:
      - "8931:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bestellingservice

  de-jong-bestellingservice-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - "8932:80"
    links:
     - de-jong-bestellingservice-mysql:db

  de-jong-accountservice-mysql:
    image: 'bitnami/mysql:latest'
    container_name: de-jong-accountservice-mysql
    ports:
     - "8935:3306"
    environment:
     - MYSQL_ROOT_USER=root
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=accountservice

  de-jong-accountservice-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
     - "8936:80"
    links:
      - de-jong-accountservice-mysql:db
