---
version: '3'
services:

  de-jong-webwinkel-mysql:
    image: 'bitnami/mysql:latest'
    ports:
      - "8925:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webwinkel

  de-jong-phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
    - "8926:80"
   links:
     - de-jong-webwinkel-mysql:db

  de-jong-webwinkel:
    build:
      context: .
      dockerfile: ops/Webwinkel/Dockerfile
    command: sh ./wait-for.sh --timeout=300 de-jong-webwinkel-mysql:3306 -- java -jar app.jar
    ports:
      - "8927:8081"
    environment:
      - spring_datasource_url=jdbc:mysql://de-jong-webwinkel-mysql:3306/webwinkel
    depends_on:
      - de-jong-webwinkel-mysql

  de-jong-front-end-webwinkel:
    build:
      context: .
      dockerfile: ops/Polymer/Dockerfile
    ports:
      - "8928:8081"

  de-jong-replayservice:
      build:
        context: .
        dockerfile: ops/Replayservice/Dockerfile
      command: java -jar app.jar
      ports:
        - "8929:8080"
