server:
  port: 9999

spring:
 datasource:
   driverClassName: com.mysql.jdbc.Driver
   url: jdbc:mysql://192.168.99.100:8935/accountservice
   username: root
   password: root
 jpa:
   hibernate:
     ddl-auto: create-drop

tokens:
  refreshToken:
    privateKey: "-----BEGIN RSA PRIVATE KEY-----
                 MIIJKAIBAAKCAgEA0WKSV9Ux/YWTFX7vUhT8GgCjPOEd57uTi/5c9sZ0Kcsix55o
                 jTV5IJsYDpU4/0prMFj1lvKuPPfakn6m0P6FYFHsS+aDdA7EePcn6XpYC71mIYwu
                 MG0+x2JNRTrdRLrZsWAEevOf3agFi0r330fR0K/oF7Ln5zjMKAV0wNQ3qPaQI2TQ
                 VR4Or5kb7drIivedIjnyht7pAxGI+5j6gY0hue0J8XcBtf0aAvdh3P5qUVi99sLm
                 DQuhcbQu61A0mScarvJEMXFRfWMHCvue01AuzgoI6cVOqaOskIt+XX03tcUE73rV
                 +gFdg+tOGllyK2hncKvZfwc1C2G1n2IaffGGBQMzKWdPwggbqwgBQOiJlZmRdpX6
                 JUdR4kbQ7lph/gQFPwPSxyyr6dfHw24C+ZDOptQlbaDHx6+FxNchy51sID0V7Vn2
                 O2rpvenGxmpaPyHZQd0JXKoCG5qnW5zKnWCh+xFBJjqa2A1mRm1Qjs+rbRjpE7Bn
                 MrboEiVrED6+kByLO0SiWy23FjBcWC8UlfjhGyQ/nZfe93dpWPgaXDAWFc8Y7FQ2
                 8IGfkbHCciyW1WoOXukYHZDwiuMFWS4bhI1yJsNSoTu7wYFwyYsfcvuSnKaijgBa
                 cUgzLKOWcEj+UlAPQ1fP/ww2jPrcMNiCS5kTGERMekoeG9r+nOIu6E31aikCAwEA
                 AQKCAgBiV7a+VB7noR4lAXpsBfkmSVhiFqWSGpLBNNX6/di/bG5IbYlTkWLzwoR5
                 DPM5TH2ttoqavB7D+fGJzryQ+oowZCnkuD7TesAixIrVaSYDVZCrfwiOrDDJOs1q
                 D6yvREdMvPk9ukFCvVDlTG/BSh0stAIBZ4DuI8oXngBpNQNzc2LdjNMgtz5UkUgB
                 3jlEs+n0klzrpbSxQUIiUYaO5HeLuN5rr+Z40IiwDfrD7iaHUHPge0fLpsPMAMHs
                 ub4KlMg+lQEca8nHZ4R+TxIY09c35JStH4PDv2Ekfq/6Pv60e/XGeN4ZTxzaAeGs
                 FIjABIhY7g34UK1ETD8evdgNgSvdQu2pXHfNPFEyyVsz23rMdYGb0IEDHSc1LfVw
                 LfUjMPQtWcWv6ic4CelbBkxgXrm35pc/YO5bbpA9ipmYHbqng5fM510xeyoxEm/i
                 ywgObBaLigwLgaa+uZ+DPBqmSdEGwJqUu1zcxt8jm+xVW833tw1W3umboAkmqjL/
                 Wcn4D85k8kSdB/zwkyomlhYScgFWHOqGL8ZntATf3oyBy7HnxGkCJzLVn42dlxM5
                 XgbrhlovwcYz6jnq+20PUDbm/mF6SzvUfVNmkC/r8tJnIXYijW+19UTJMO8gQ2lg
                 jplIyPL4+4JzvxzemHoRnVsqXNRXOjxJUKW0oqAC1YvyN2rZBQKCAQEA9lZyJnag
                 yxRduDm6mGMSE7Ob6zMvAPGiU2cAMHYeFhjxNd4p3eUq8pBJBi7uDPkMP8YY1+aB
                 p9UNSRxuyuNlqyNW6oNe6OMzKOLt7HXyhEEcjMU6eKUGQec7mnblAC4bvobYBGaJ
                 cSJGG3LO9ZbyxwjJG/WsyFi7Xn4l24KoXgGsQvMbJ3B8MJRUw7EZLPJ6RZKV90KQ
                 UsUbf3Z11ZMFP0fLuX7u/WGwZg+0HbZyu6hgm7gvFfA8N7RRO6WC4+CE04p69sst
                 NPsWpmUUi0rQCXvD/NHxOp6ZpLXhUeudR8uZ64EgURfb7C5Ztz+ZBRt0tgfB97D6
                 y6fxnCKiwwB/nwKCAQEA2ZkSnu05yeUrPcgpzKf1DaNb/AAtNMQ/m8QZoenvh+5M
                 JD4BM83FlL1pqIvkGckwnuiXm9z8xJFnP7eLYrVDabmQOskob/9WcZsr4HsJsF+8
                 YjV/6ubD44Gd9DB8plpVwfqkQg0EaxSmTEte/jjgTw5oon6xSligB1eOvPHjBa8W
                 DtILkLnidnTOP4MNv/MNTWrX/HT8Sx5hwQbVdd5UYgBcuZUkr2duAJDMPHeH3y3P
                 9hTsvRrLbUwzfd++qwU48HAVwlVWpkcBzjpj3L8HcTpr/gm02948EFIO76wkFbbx
                 Ggr2CczZJlweV+Mhn8vb0pH4aXSUIxGpG0sB5AmhNwKCAQEAiz1JwJwFP0T/xIY9
                 Bq3ZJfG8DDIeO3ZZvrLV1I6vauYmUcCGAbrrj7gmzqvwOrz7Q4EBwee1Gdy/abf8
                 mAn5Cccr9drT5ueln1LGEYaJ0l/Ld3Z0GoWNB+tgMWtK/dMSM5uctsAOqDgrUJCQ
                 kxkDmaVJp9gyFfyxzDOZyn4MFTb029L2YlCeogb18rdD97gHjRPSWLTzRxXK+T1I
                 VbSInsBCU1OAWxDA2K+/q5vZNmFyWhK96rSkFQiDcieX2J6r9bas0pr9rpjOsLcp
                 6aIb/YBLw7gXln7XcdasydVYTaC0G/4c+jl2QgXhCEeWguCGE+5GoW8UE9GWLB8X
                 yQmbGQKCAQBqrPmNAl2/VeNCEZw0Ye7oNbsFqwx+fut0MMokL6ynZjLb3a33OJzx
                 k352C8bSwWhdr0eMOOWOdH46pX/m71hSP4+u0ilJ5tL5NQporckNN5ICT5objfBg
                 242VRiQF5el/BKJ8YydUW7Y/VwAF/9ovx6+SYiwGd7ZUgx9OEAOtKK3WrDDRTd/x
                 FMh8KIKYJM7TslqawLtjFEz2NaR2eX3C4cyTisOGXl12V4ZY6nyo9Cusx4tcFgO+
                 3Imt3v/5lcDZVwnD0NR/BfajpMqKUPiUEQEadKW+2I93rNL3utuh7aL7kn4WRd/7
                 R1P04Dv+vBFThQ5UnLt3CdRutfICWpo3AoIBADRdGgw7kOvXPJJH8t9E+YyH0C7s
                 TaYcWDYVCx1TdtaXWlTKlaiSk1Qz2V85iAtZX6Mqk4DZooVSwmwtNfscEO1Rz3nC
                 e09YmJDw/KwEmrHTmgOD+kcH3ogiM4syBscu3ISr+JNlpeNQDbzu5EYU3bGQW5nh
                 bJYc9TfXKHqsp0+OimyzKGoFlTNO7ev4FMR6nZbEW+NXeNQD/skxhV73oX006Xx9
                 9eimgNwlMEeyo6vpMtwYcaBP48R4nwbARGOFVBlhCaXv8wTVdu92XZI9AwO6MZ3B
                 BtBn1iWvY7oqfT5jn76KBzZT0iUu9CXA8nJoujB8J+BpJbf8Z2rhYnMUQEE=
                 -----END RSA PRIVATE KEY-----
"
    publicKey: "-----BEGIN PUBLIC KEY-----
                MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0WKSV9Ux/YWTFX7vUhT8
                GgCjPOEd57uTi/5c9sZ0Kcsix55ojTV5IJsYDpU4/0prMFj1lvKuPPfakn6m0P6F
                YFHsS+aDdA7EePcn6XpYC71mIYwuMG0+x2JNRTrdRLrZsWAEevOf3agFi0r330fR
                0K/oF7Ln5zjMKAV0wNQ3qPaQI2TQVR4Or5kb7drIivedIjnyht7pAxGI+5j6gY0h
                ue0J8XcBtf0aAvdh3P5qUVi99sLmDQuhcbQu61A0mScarvJEMXFRfWMHCvue01Au
                zgoI6cVOqaOskIt+XX03tcUE73rV+gFdg+tOGllyK2hncKvZfwc1C2G1n2IaffGG
                BQMzKWdPwggbqwgBQOiJlZmRdpX6JUdR4kbQ7lph/gQFPwPSxyyr6dfHw24C+ZDO
                ptQlbaDHx6+FxNchy51sID0V7Vn2O2rpvenGxmpaPyHZQd0JXKoCG5qnW5zKnWCh
                +xFBJjqa2A1mRm1Qjs+rbRjpE7BnMrboEiVrED6+kByLO0SiWy23FjBcWC8Ulfjh
                GyQ/nZfe93dpWPgaXDAWFc8Y7FQ28IGfkbHCciyW1WoOXukYHZDwiuMFWS4bhI1y
                JsNSoTu7wYFwyYsfcvuSnKaijgBacUgzLKOWcEj+UlAPQ1fP/ww2jPrcMNiCS5kT
                GERMekoeG9r+nOIu6E31aikCAwEAAQ==
                -----END PUBLIC KEY-----
"
  accessToken:
    privateKey: "-----BEGIN RSA PRIVATE KEY-----
                 MIIJJwIBAAKCAgEAzRbJGLZ5Gq8iVYt/ynQb/KTgXHmfS3DmbymVRpYtER9lyuxm
                 UbilJcGr5YooWXLTyI+1IzOHmhJgiqwHbYB36gOADNHZ3+tDBihHF/uzJ+6zQLX0
                 NaWX1vrHZfNE8EgYHGWmyLVb+FJWAO3m+gfDrVobBVLeiblhar25JwvvUSgXfkT1
                 yRgKZWmk2ImuLFr2ftdtKaiU0jBJ4nczATaX2LQI5T0DkP66gyh/OMC2LfwGjIAg
                 9SR0krBSfLrg7Dl720Gvjdqq07OoQ+6hTUsS2dYhw10gGVi7pi1f1ymgic0I6G4V
                 giDVruYZK2CTXy9Nf/05EltxDlKBF1s9Prl7YlFz0qTjZZi6YbLyDkRbkI10OIXz
                 ja1LyAkmSLXqMPqehbygHL2OrytKCoM/nydGe63NNqozV5qknjrbqvcLCLuQ2uQb
                 NfDJcoiCLskDPrn1/yQ6GM/lTzOsKo6OQJVZ5+WzBkLaDtEdrjLoag4dwcmjj3g5
                 oBqMdpyNsfaUu2H8e3xEG+tF3peDoCO942C/+fKdRGgWHoEDmYgqy31Zp7xmuQLE
                 OSftpvWgV6bHp4+bPVgvZU2H/4QToXiXMwdntjeX41A9LuWDH3jHPYkGO5Nq1ay4
                 x3gJb5odc3oLFJpRHeoBHXl58Q8byvmKlFrXNPfFu9QGWItsEQMJmrussEECAwEA
                 AQKCAgA06uIsfDi3R+UmCX6JsHfgMnKpqcAOaS0sFaCsu+cY+e778w9bmrcSDOzb
                 p1BN9DDtGRd147/jY0aBwW2RNYq7WPfbVvJOspdyqUXezFUnwpGB6vD+PqH1GHQG
                 vERXc2K1QQ1N0G3Qnv4N81SbwxEcU5mRQBanlquqLRXvG0c+u4eETyrUHl3gWOft
                 72h/jWD4zYEfNJ5htY/63SLN91Yq1hlNfPbEnNVnLjXVYPQg3VybOBxI5IUnrFM8
                 V8Pdb9+jbUls4rUdNsf97z6zgOF2T6gajpbPs3OHp0GJdPY1WDAqOO1XzD0WicyI
                 wryD3OK0WZQ2Rl3fgi5I5oPhAV7yQy8bqiSWaSO6oy8JouR2O2e6/fMayfPheqJ9
                 9U/hL47unherigAPW2GOJgZdEr+aDcf97+PpwiPc3bx2BUYVW9mCZaNI/YJG5sFT
                 tMIOhalUHM8sjc8cLce5kxDs1U4VDudCuscOhpxcxjHna89TEcQIHcy2b0bw61Bl
                 ag1ayOlVid5oeIXNzjN3Az8kUXe0QMrK6nUFofYVMzkLA/EDln6HpeF9liXChWQz
                 3L1oPSe/w5tC3/qmbPoBn6ZVFVD3ohJeSUZkUg4YPhV/nECvax+i8aY9gW5eOJZN
                 CcWvakWFhdswoo/ADpI62suDXdtVFUpuqURCB0qBfom7e5sxoQKCAQEA5apS/SNF
                 ai4RhlhhbLqQQ8uKipOaR+49R1GA0Vna8OAdJJoPVbvuvWgO399MwgKTuGGti6G6
                 0ak/JAobDjMsoFoTrKDHqOWQ6rmNeQrNJnUNSJJNJK0iiLAgEFT/hArNnQwMzW4A
                 xD6U7ztnO45t4p54KeRXvtiSTfePB7aeYb6mQ94Z+G8nABQZO+y0T/fM7lcc9F9F
                 JLjQVK2twSqmZrGorr0vKIptgiz3lc9P+G8LR847+JgONoga2FhnDWLX24QD1UHY
                 xdv3UKNhNGgS/hptCXmHZjAIpzoD5D+X4mt+DvdJsAi67D+mbTrQI2qISfPsLA5A
                 IbSZp50vPDhKnQKCAQEA5JsKGOz1fnrQ3zb8p/CN9dHhwxYuuYcnC0kwx1FZtc/B
                 Uq7MApwzV6zaL/qxRRHQcSpSOi8+pnDGKUxfh4dAFcf1Ckcw5Tm2i6TN6Rbxxvp7
                 3OCbTNFhjMyDrwYtQym0M7HwzHGyduvyIwajuUv57h5YOXWGbZs+G4SYMViqbNjC
                 IIKN+FCcdmIYcNpN2Ve6UPuF/bjYlrPc8+6A4WUO96HGSt3HPX9fbq+jwOVfk0wY
                 N2RslzFOeUpEkI/euVg1mt/CW8FE+sSkoHAyLBn4UreIzb1HpOk+JmIf3LmisAKx
                 wmGgOjEDS22Tj9F5h8WGq7Ubv8iw1sUMlM/aNDvo9QKCAQBLHbE1ACNE/jpXIXMD
                 9+UVd24hsvMkEaTTPbIPRv9YB0Ug4o6fcO893dn3mPZnAibEiJYVdFlBF8UCCZgd
                 xdkTvUJwFMoY0LTcQMIn08OTj3c/xDIdC8+eu1RRYyuLSWlEs1tAmXkAtqNJt7kk
                 /omsND6DHR8h2X3IqG6MjEszFwMUcYE3A0vTN7+lHN9AxICvd6iNuNdJknT5LTEG
                 W+e+8N6GAHR7IwN8Ly7vPbYfQFqFKsvsm/cSGOQG3Ksf8rM9JemHB5lZ5X73TeiO
                 FngXyhbdoXUKlC1QXKZHMhGASb4aMQFV5RUWDh9l3HWVD9PxtCkLo8GQBJy4+K0p
                 WhP1AoIBABAZ+3QV/JSUAfI25UTO5LDTv5sGDPR0WIOq/AyN5kuv/mXcefIVHmim
                 fBe1CJdc0dmmqXP/r+H5P3vZLUFWfWULWG8I5KDAl+LuELLCMvVY3zCHgWi/tqc8
                 IGpLfRSl81NQzS0ZNQC7Taq55P5AI7Jp4LzrUjSWIqG9jRqsrBROkB3KFEXRJ7QO
                 5LnOJn2QeEcL8DwWsOqscHud6OX3QD6g3l6XkFj8h7Q8GsSTY0/0pCACqsNbbbON
                 T5b/Cyjy1ZO6/u2Hh1xCTXYfcOk6SwtIchJLqqgq5X2+m4/oY1USW4LdbXOr0BeX
                 +DTBBFZTy1B8yR+Q+yOlbWVt3mifb6ECggEADo3KezPG9J3adn4aDku5sy2wqd1w
                 1dlgEBB+7mwv+rXVJ7ys+lNCbMfBVZpicPERudr6Gr7AdPBd51f011bj00dQhPpU
                 HFOGW8HDL0Yo4IAbcQ1GQ2otjB3c2FjzmgtnQj5APphSKVAc7sAsqFPMk9HLNsQj
                 ycom5Avl6vv02Xm+k8P0ChaseTmC/2emuRS+xlyn3Qy+4LaH7aPrDXUlzetf7ukn
                 5d4VI60ljY5p/gQVmETXfJARL+pMDL9hUi0BJ4s0p2tqhqcv4nd5FNV1C/vpfwDT
                 bKiOipGZTun2G94X2fmtEvCnirieAaP8MJIUfFwlNm10x7Fmo7jbT6RJMQ==
                 -----END RSA PRIVATE KEY-----
"
    publicKey: "-----BEGIN PUBLIC KEY-----
                MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAzRbJGLZ5Gq8iVYt/ynQb
                /KTgXHmfS3DmbymVRpYtER9lyuxmUbilJcGr5YooWXLTyI+1IzOHmhJgiqwHbYB3
                6gOADNHZ3+tDBihHF/uzJ+6zQLX0NaWX1vrHZfNE8EgYHGWmyLVb+FJWAO3m+gfD
                rVobBVLeiblhar25JwvvUSgXfkT1yRgKZWmk2ImuLFr2ftdtKaiU0jBJ4nczATaX
                2LQI5T0DkP66gyh/OMC2LfwGjIAg9SR0krBSfLrg7Dl720Gvjdqq07OoQ+6hTUsS
                2dYhw10gGVi7pi1f1ymgic0I6G4VgiDVruYZK2CTXy9Nf/05EltxDlKBF1s9Prl7
                YlFz0qTjZZi6YbLyDkRbkI10OIXzja1LyAkmSLXqMPqehbygHL2OrytKCoM/nydG
                e63NNqozV5qknjrbqvcLCLuQ2uQbNfDJcoiCLskDPrn1/yQ6GM/lTzOsKo6OQJVZ
                5+WzBkLaDtEdrjLoag4dwcmjj3g5oBqMdpyNsfaUu2H8e3xEG+tF3peDoCO942C/
                +fKdRGgWHoEDmYgqy31Zp7xmuQLEOSftpvWgV6bHp4+bPVgvZU2H/4QToXiXMwdn
                tjeX41A9LuWDH3jHPYkGO5Nq1ay4x3gJb5odc3oLFJpRHeoBHXl58Q8byvmKlFrX
                NPfFu9QGWItsEQMJmrussEECAwEAAQ==
                -----END PUBLIC KEY-----
"

logging:
  level:
    org:
      springframework:
        security: DEBUG
