spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:8925/webshop_kantilever
    username: root
    password: root
  rabbitmq:
    username: Kantilever
    password: Kant1lever
    host: 192.168.178.158
    port: 8920

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 8920

logging:
  level:
    org:  FINE

